spring:
  datasource:
    url: ${SCHEDULER_DATASOURCE_URL}
    username: ${SCHEDULER_DATASOURCE_USERNAME}
    password: ${SCHEDULER_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: ${SCHEDULER_KAFKA_BOOTSTRAP}
    consumer:
      group-id: scheduler-consumer-group
      auto-offset-reset: earliest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

logging:
  level:
    org.springframework.kafka: INFO
    org.example.scheduler: DEBUG
