# === ОБЩИЕ НАСТРОЙКИ (для всех модулей) ===
bot:
  token: ${TELEGRAM_BOT_TOKEN}
  username: ${TELEGRAM_BOT_USERNAME}

spring:
  main:
    allow-bean-definition-overriding: true

  datasource:
    url: jdbc:postgresql://localhost:5432/telegrambot
    username: bot_user
    password: bot_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
#      ddl-auto: update это для проды не обновляет бд
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: my-consumer-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  logging:
    level:
      org.springframework.kafka: INFO
      org.example.scheduler: DEBUG



